[package]
name = "factory"
version = "0.1.0"
edition = "2021"

[lib]
name = "lexer"
path = "src/lexer.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
